[Shapefill0]
Meter=Roundline
X=25
Y=20
W=80
H=80
StartAngle= 0
RotationAngle=100
LineLength=52
Solid = 1
LineColor=#Color4#
AntiAlias=1



[3]
Meter=Roundline
X=25
Y=20
W=80
H=80
StartAngle= (Rad(90))
RotationAngle=(Rad(-360))
LineLength=42
Solid = 1
LineColor=#Color5#
AntiAlias=1
DynamicVariables=1

[0]
Meter=Roundline
MeasureName=mBand0
X=25
Y=20
W=80
H=80
StartAngle=(Rad(90))
RotationAngle=(Rad(360))
LineLength=42
Solid = 1
LineColor=#Color1#
AntiAlias=1
DynamicVariables=1

[2]
Meter=Roundline
X=25
Y=20
W=80
H=80
StartAngle= (Rad(270))
RotationAngle=(Rad(-360))
LineLength=32
Solid = 1
LineColor=#Color3#
AntiAlias=1
DynamicVariables=1

[1]
Meter=Roundline
MeasureName=mBand1
X=25
Y=20
W=80
H=80
StartAngle= (Rad(270))
RotationAngle=(Rad(360))
LineLength=32
Solid = 1
LineColor=#Color2#
AntiAlias=1
DynamicVariables=1